# Generated by Django 5.2.14 on 2026-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('customer', 'Customer'), ('business', 'Business')], default='customer', max_length=50),
        ),
    ]
