# Generated by Django 5.2.14 on 2026-05-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoderrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('location', models.CharField(default='', max_length=100)),
                ('tel', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('working_hours', models.CharField(default='', max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coderr_profile', to='auth_app.profile')),
            ],
        ),
    ]
