# Generated by Django 5.2.14 on 2026-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderrprofile',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
