# Generated by Django 5.2.14 on 2026-05-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0004_alter_offerdetail_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(default='basic', max_length=100),
            preserve_default=False,
        ),
    ]
