# Generated by Django 5.2.14 on 2026-06-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_profile_type'),
        ('coderr_app', '0008_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_user',
        ),
        migrations.AddField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='auth_app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='order', max_length=100),
            preserve_default=False,
        ),
    ]
