# Generated by Django 5.2.14 on 2026-06-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderr_app', '0009_rename_customer_order_customer_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time_in_days',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='features',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='order',
            name='offer_detail',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='coderr_app.offerdetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='offer_type',
            field=models.CharField(default='premium', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coderr_app.offer'),
        ),
    ]
