# Generated by Django 5.2.14 on 2026-06-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_profile_type'),
        ('coderr_app', '0012_alter_offerdetail_delivery_time_in_days_review'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_business',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reviewer_user',
            new_name='reviewer',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('reviewer', 'business_user'), name='unique_review_per_business'),
        ),
    ]
